library(zoo)
library(xts)
library(dplyr)
library(lmtest)
library(sandwich)
library(urca)

dir.create("results", showWarnings = FALSE)
df <- read.csv("data/macro_timeseries_clean.csv", stringsAsFactors = FALSE)
df$date <- as.Date(df$date)
xts_data <- xts(df[, -1], order.by = df$date)

sink("results/statistical_tests.txt", split = TRUE)

cat("=== AUGMENTED DICKEY-FULLER TESTS ===\n\n")
adf_inflation <- ur.df(as.numeric(xts_data$inflation), type = "drift", selectlags = "AIC")
cat("Inflation:\n")
print(summary(adf_inflation))
cat("\n")
adf_unemployment <- ur.df(as.numeric(xts_data$unemployment), type = "drift", selectlags = "AIC")
cat("Unemployment:\n")
print(summary(adf_unemployment))
cat("\n")
adf_interest_rate <- ur.df(as.numeric(xts_data$interest_rate), type = "drift", selectlags = "AIC")
cat("Interest rate:\n")
print(summary(adf_interest_rate))
cat("\n")
adf_industrial_production <- ur.df(as.numeric(xts_data$industrial_production), type = "drift", selectlags = "AIC")
cat("Industrial production:\n")
print(summary(adf_industrial_production))
cat("\n")

cat("=== SHAPIRO-WILK NORMALITY TESTS ===\n\n")
vars_norm <- c("inflation", "unemployment", "interest_rate", "industrial_production")
for (v in vars_norm) {
  x <- as.numeric(xts_data[, v])
  if (length(x) > 5000) x <- sample(x, 5000)
  sw <- shapiro.test(x)
  cat(v, ":\n")
  print(sw)
  cat("\n")
}

cat("=== LINEAR REGRESSION ===\n\n")
fit <- lm(inflation ~ unemployment + interest_rate + industrial_production, data = df)
print(summary(fit))
cat("\n")

cat("=== BREUSCH-PAGAN TEST (Heteroskedasticity) ===\n\n")
bp <- bptest(fit)
print(bp)
cat("\n")

cat("=== VARIANCE INFLATION FACTORS ===\n\n")
m1 <- lm(unemployment ~ interest_rate + industrial_production, data = df)
m2 <- lm(interest_rate ~ unemployment + industrial_production, data = df)
m3 <- lm(industrial_production ~ unemployment + interest_rate, data = df)
vif_unemployment <- 1 / (1 - summary(m1)$r.squared)
vif_interest_rate <- 1 / (1 - summary(m2)$r.squared)
vif_industrial_production <- 1 / (1 - summary(m3)$r.squared)
cat("VIF unemployment:", vif_unemployment, "\n")
cat("VIF interest_rate:", vif_interest_rate, "\n")
cat("VIF industrial_production:", vif_industrial_production, "\n\n")

cat("=== DURBIN-WATSON TEST (Autocorrelation) ===\n\n")
dw <- dwtest(fit)
print(dw)

sink()
